INSERT
INTO MWP_GALLERY_ALBUM
(
    ALBUM_NAME,
    ALBUM_EVENT_DATE,
    ALBUM_ISPUBLISHED,
    ALBUM_ISDELETED,
    ALBUM_USERNAME,
    ALBUM_TIMESTAMP,
    ALBUM_ISFEATURED,
    TEMP_ID
)

SELECT 
  GALLERY_ALBUM_NAME,
  GALLERY_ALBUM_EVENT_DATE,
  1,
  0,
  USER_NAME,
  GALLERY_ALBUM_DATE,
  0,
  GALLERY_ALBUM_ID
FROM PORTAL.TBL_PHOTO_GALLERY_ALBUM ;