INSERT
INTO MWP_BANNER_TEMPLATE
  (
    BANNER_USERNAME,
    BANNER_IMAGENAME,
    BANNER_START_TIMESTAMP,
    BANNER_END_TIMESTAMP,
    BANNER_TIMESTAMP,
    BANNER_TITLE,
    BANNER_TYPE,
    BANNER_HTMLFILE,
    BANNER_ISDELETED,
    BANNER_IPADDRESS,
    BANNER_FOLDER,
    TEMP_ID
  )



SELECT 
  TEMPLATE_USERNAME,
  TEMPLATE_IMAGENAME,
  TEMPLATE_STARTTIMESTAMP,
  TEMPLATE_ENDTIMESTAMP,
  TEMPLATE_TIMESTAMP,
  TEMPLATE_TITLE,
  TEMPLATE_TYPE,
  TEMPLATE_HTMLFILE,
  TEMPLATE_DELETE,
  TEMPLATE_IPADDRESS,
  TEMPLATE_FOLDER,
  TEMPLATE_ID
FROM PORTAL.TBL_TEMPLATE_MANAGEMENT ;