DECLARE 
	CURSOR c IS SELECT FORUM_CATEGORY_NAME,FORUM_CATEGORY_DESCRIPTION,FORUM_CATEGORY_ID FROM PORTAL.TBL_FORUM_CATEGORY ;
	rc c%ROWTYPE;
BEGIN
	OPEN c;
	LOOP
	FETCH c INTO rc;
	EXIT WHEN c%NOTFOUND;
  
  INSERT
  INTO MWP_FORUM_CATEGORY
    (
      FORUM_CATEGORY_NAME,
      FORUM_CATEGORY_DESCRIPTION,
      TEMP_ID
    )
  VALUES(rc.FORUM_CATEGORY_NAME,rc.FORUM_CATEGORY_DESCRIPTION,rc.FORUM_CATEGORY_ID);
END LOOP;	
COMMIT;
END;