INSERT
INTO MWP_MAKATI_VIDEOS
  (
    MAKATI_VIDEO_USERNAME,
    MAKATI_VIDEO_TIMESTAMP,
    MAKATI_VIDEO_TITLE,
    MAKATI_VIDEO_TYPE,
    MAKATI_VIDEO_ISPUBLISHED,
    MAKATI_VIDEO_ISDELETED,
    MAKATI_VIDEO_IPADDRESS,
    MAKATI_VIDEO_DESCRIPTION,
    TEMP_ID
  )

SELECT 
  WEBCAST_USERNAME,
  WEBCAST_TIMESTAMP,
  WEBCAST_TITLE,
  WEBCAST_TYPE,
  1,
  WEBCAST_DELETE,
  WEBCAST_IPADDRESS,
  WEBCAST_DESC,
  WEBCAST_ID
FROM PORTAL.TBL_WEBCAST ;