begin
  for o in (SELECT MAKATI_VIDEO_ID, TEMP_ID FROM MWP_MAKATI_VIDEO_FILE)
  loop
    EXECUTE IMMEDIATE '
    INSERT
	INTO MWP_MAKATI_VIDEO_THUMBNAIL
	  (
	    MAKATI_VIDEO_ID,
	    TEMP_FILE
	  )

    SELECT 
      '|| o.MAKATI_VIDEO_ID ||',
      WEBCAST_IMAGENAME
    FROM PORTAL.TBL_WEBCAST WHERE WEBCAST_ID = ' || o.TEMP_ID;
  end loop;
end;
