--PLEASE EXECUTE THE SCRIPTS BELOW SEQUENTIALLY



--IMPORT TBL_DOWNLOADS_TYPE

INSERT INTO MWP_DOWNLOADS_CATEGORY
  (DOWNLOADS_CATEGORY_PARENT_ID,
    DOWNLOADS_CATEGORY_NAME,
    DOWNLOADS_CATEGORY_ISPUBLISHED,
    DOWNLOADS_CATEGORY_ISDELETED,
    DOWNLOADS_CATEGORY_TIMESTAMP,
    DOWNLOADS_CATEGORY_ROW,
    TEMP_ID,
    TEMP_TYPE)
SELECT 
  0,DOWNLOADS_TYPE_NAME,1,0,SYSTIMESTAMP,0,DOWNLOADS_TYPE_ID,'TYPE'
FROM PORTAL.TBL_DOWNLOADS_TYPE ;



--IMPORT TBL_DOWNLOADS_CATEGORY

begin
  for o in (SELECT DOWNLOADS_CATEGORY_ID, TEMP_ID FROM MWP_DOWNLOADS_CATEGORY where TEMP_TYPE = 'TYPE')
  loop
    EXECUTE IMMEDIATE '
    INSERT
      INTO MWP_DOWNLOADS_CATEGORY
      (DOWNLOADS_CATEGORY_PARENT_ID,
       DOWNLOADS_CATEGORY_NAME,
       DOWNLOADS_CATEGORY_ISPUBLISHED,
       DOWNLOADS_CATEGORY_ISDELETED,
       DOWNLOADS_CATEGORY_TIMESTAMP,
       DOWNLOADS_CATEGORY_ROW,
       TEMP_ID,
       TEMP_TYPE)
    SELECT 
      '|| o.DOWNLOADS_CATEGORY_ID ||',
      DOWNLOADS_CATEGORY_NAME,
      1,
      0,
      SYSTIMESTAMP,
      0,
      DOWNLOADS_CATEGORY_ID,
      ''CATEGORY''
    FROM PORTAL.TBL_DOWNLOADS_CATEGORY WHERE DOWNLOADS_CATEGORY_TYPE = ' || o.TEMP_ID;
  end loop;
end;



--IMPORT TBL_DOWNLOADS_SUBCATEGORY

begin
  for o in (SELECT DOWNLOADS_CATEGORY_ID, TEMP_ID FROM MWP_DOWNLOADS_CATEGORY where TEMP_TYPE = 'CATEGORY')
  loop
    EXECUTE IMMEDIATE '
    INSERT
      INTO MWP_DOWNLOADS_CATEGORY
      (DOWNLOADS_CATEGORY_PARENT_ID,
       DOWNLOADS_CATEGORY_NAME,
       DOWNLOADS_CATEGORY_ISPUBLISHED,
       DOWNLOADS_CATEGORY_ISDELETED,
       DOWNLOADS_CATEGORY_TIMESTAMP,
       DOWNLOADS_CATEGORY_ROW,
       TEMP_ID,
       TEMP_TYPE)

    SELECT 
      '|| o.DOWNLOADS_CATEGORY_ID ||',
      DOWNLOADS_SUBCATEGORY_NAME,
      1,
      0,
      SYSTIMESTAMP,
      0,
      DOWNLOADS_SUBCATEGORY_ID,
      ''SUB-CATEGORY''
    FROM PORTAL.TBL_DOWNLOADS_SUBCATEGORY WHERE DOWNLOADS_CATEGORY_ID = ' || o.TEMP_ID;
  end loop;
end;