--PRE REQUISITE MWP_DOWNLOADS_CATEGORY


begin
  for o in (SELECT DOWNLOADS_CATEGORY_ID, TEMP_ID FROM MWP_DOWNLOADS_CATEGORY where TEMP_TYPE = 'CATEGORY')
  loop
    EXECUTE IMMEDIATE '
    INSERT INTO MWP_DOWNLOADS_CONTENT
    (
        DOWNLOADS_CONTENT_CATEGORY_ID,
        DOWNLOADS_CONTENT_TITLE,
        DOWNLOADS_CONTENT_DESCRIPTION,
        DOWNLOADS_CONTENT_LINK,
        DOWNLOADS_CONTENT_ISPUBLISHED,
        DOWNLOADS_CONTENT_ISDELETED,
        DOWNLOADS_CONTENT_TIMESTAMP,
        DOWNLOADS_CONTENT_ROW,
        TEMP_ID
    )


    SELECT 
        '|| o.DOWNLOADS_CATEGORY_ID ||',
        DOWNLOADS_TITLE,
        DOWNLOADS_DESC,
        DOWNLOADS_LINK,
        DOWNLOADS_PDF,
        DOWNLOADS_THUMB,
        DOWNLOADS_TIMESTAMP,
        DOWNLOADS_STATUS,
        DOWNLOADS_SORT_ORDER,
        DOWNLOADS_SUBCATEGORY
    FROM PORTAL.TBL_DOWNLOADS ;

    SELECT 
      '|| o.DOWNLOADS_CATEGORY_ID ||',
      DOWNLOADS_CATEGORY_NAME,
      1,
      0,
      SYSTIMESTAMP,
      0,
      DOWNLOADS_CATEGORY_ID,
      ''CATEGORY''
    FROM PORTAL.TBL_DOWNLOADS_CATEGORY WHERE DOWNLOADS_CATEGORY_TYPE = ' || o.TEMP_ID;
  end loop;
end;