
--PLEASE RUN THIS CODE SEQUENTIALLY
--CHANGE THE DYNAMIC_MENU_USER to ACCEPT NULL VALUES AND MAKE THE DATA to 150
--TBL_MENU_FIRST_LEVEL_NEW to MWP_DYNAMIC_MENU

INSERT
INTO MWP_DYNAMIC_MENU
  (DYNAMIC_MENU_LABEL,DYNAMIC_MENU_PARENT,DYNAMIC_MENU_ISPUBLISHED,DYNAMIC_MENU_ISDELETED,DYNAMIC_MENU_USER,DYNAMIC_MENU_TIMESTAMP,DYNAMIC_MENU_ROW,TEMP_ID,TEMP_CONTENT_ID)
  
SELECT
  FIRST_LEVEL_LABEL,0,FIRST_LEVEL_STATUS,0,NULL,SYSTIMESTAMP,FIRST_LEVEL_SORT_ORDER,FIRST_LEVEL_ID,CONTENT_ID
FROM PORTAL.TBL_MENU_FIRST_LEVEL_NEW ;
  
--TBL_MENU_SECOND_LEVEL_NEW to MWP_DYNAMIC_MENU
begin
  for o in (SELECT DYNAMIC_MENU_ID, TEMP_ID FROM MWP_DYNAMIC_MENU where DYNAMIC_MENU_PARENT = 0)
  loop
    EXECUTE IMMEDIATE '
    INSERT INTO MWP_DYNAMIC_MENU(DYNAMIC_MENU_LABEL,DYNAMIC_MENU_PARENT,DYNAMIC_MENU_ISPUBLISHED,DYNAMIC_MENU_ISDELETED,DYNAMIC_MENU_USER,DYNAMIC_MENU_TIMESTAMP,DYNAMIC_MENU_ROW,TEMP_ID,TEMP_CONTENT_ID)
    SELECT
      SECOND_LEVEL_LABEL,'|| o.DYNAMIC_MENU_ID ||',SECOND_LEVEL_STATUS,0,NULL,SYSTIMESTAMP,SECOND_LEVEL_SORT_ORDER,SECOND_LEVEL_ID,CONTENT_ID
    FROM PORTAL.TBL_MENU_SECOND_LEVEL_NEW WHERE FIRST_LEVEL_ID = ' || o.TEMP_ID;
  end loop;
end;



--TBL_MENU_NEW to MWP_DYNAMIC_MENU
begin
  for o in (SELECT DYNAMIC_MENU_ID, TEMP_ID FROM MWP_DYNAMIC_MENU where DYNAMIC_MENU_PARENT > 0)
  loop
    EXECUTE IMMEDIATE '
    INSERT INTO MWP_DYNAMIC_MENU(DYNAMIC_MENU_LABEL,DYNAMIC_MENU_PARENT,DYNAMIC_MENU_ISPUBLISHED,DYNAMIC_MENU_ISDELETED,DYNAMIC_MENU_USER,DYNAMIC_MENU_TIMESTAMP,DYNAMIC_MENU_ROW,TEMP_ID,TEMP_CONTENT_ID)
    SELECT
      MENU_LABEL,'|| o.DYNAMIC_MENU_ID ||',MENU_STATUS,0,MENU_USER,SYSTIMESTAMP,MENU_SORT_ORDER,MENU_ID,CONTENT_ID
    FROM PORTAL.TBL_MENU_NEW WHERE SECOND_LEVEL_ID = ' || o.TEMP_ID;
  end loop;
end;

