--PRE REQUISITE MWP_DYNAMIC_MENU
INSERT
INTO MWP_DYNAMIC_CONTENT
  (
   DYNAMIC_CONTENT_MENU_ID,
    DYNAMIC_CONTENT_DETAIL,
    DYNAMIC_CONTENT_TYPE,
    DYNAMIC_CONTENT_ISPUBLISHED,
    DYNAMIC_CONTENT_ISDELETED,
    DYNAMIC_CONTENT_TIMESTAMP,
    TEMP_ID
  )

SELECT
  new_data.DYNAMIC_MENU_ID,
  old_data.CONTENT_DETAILS,
  old_data.CONTENT_TYPE,
  1,
  0,  
  old_data.CONTENT_DATE_CREATED,
  old_data.CONTENT_ID
FROM PORTAL.TBL_MENU_CONTENT_NEW old_data
INNER JOIN MWP.MWP_DYNAMIC_MENU new_data ON old_data.CONTENT_ID = new_data.TEMP_CONTENT_ID
WHERE new_data.TEMP_CONTENT_ID IS NOT NULL;