DECLARE 
	CURSOR c IS SELECT CAL_CATEGORY_ID,CAL_CATEGORY_NAME,CAL_CATEGORY_DESCRIPTION FROM PORTAL.TBL_CALENDAR_CATEGORY ;
	rc c%ROWTYPE;
BEGIN
	OPEN c;
	LOOP
	FETCH c INTO rc;
	EXIT WHEN c%NOTFOUND;
	INSERT INTO MWP_EVENT_CALENDAR_CATEGORY (EVENT_CAL_CATEGORY_NAME,TEMP_ID,EVENT_CAL_CATEGORY_DESCRIPTION)
  	VALUES(rc.CAL_CATEGORY_NAME,rc.CAL_CATEGORY_ID,rc.CAL_CATEGORY_DESCRIPTION)
END LOOP;	
COMMIT;
END;